CREATE TABLE IF NOT EXISTS cats (
    id         BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name       VARCHAR(64) NOT NULL,
    created_at DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS weights (
    id          BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    cat_id      BIGINT UNSIGNED NOT NULL,
    weight_kg   DECIMAL(5,3)    NOT NULL,
    recorded_on DATE            NOT NULL,
    created_at  DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (cat_id) REFERENCES cats(id) ON DELETE CASCADE
);
